import React from 'react'
import CheckoutPayment from '../Components/CheckoutPayment';


export const metadata = {
    title: "Checkout Payment - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <CheckoutPayment/>
    </>
  )
}
