import React from 'react'
import AboutUsBG from '../Components/AboutUsBG';
import AboutUsContent from '../Components/AboutUsContent';


export const metadata = {
    title: "About Us - Online furniture store",
    description: "Generated by create next app",
  };


export default function page() {
  return (
    <>
      <AboutUsBG/>
      <AboutUsContent/>
    </>
  )
}
