import React from 'react'
import Cart from '../Components/Cart';


export const metadata = {
    title: "Cart - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <Cart/>
    </>
  )
}
