import React from 'react'
import SignUpCard from '../Components/SignUpCard'

export const metadata = {
  title: "Register - Online furniture store",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <SignUpCard/>
    </>
  )
}
