import React from 'react'
import OrderOverview from '../Components/OrderOverview'


export const metadata = {
    title: "Order Overview - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <OrderOverview/>
    </>
  )
}
