import React from 'react'
import PaymentMethods from '../Components/PaymentMethods';

export const metadata = {
    title: "Payment Methods - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <PaymentMethods/>
    </>
  )
}
