import React from 'react'
import CheckoutConfirmation from '../Components/CheckoutConfirmation';

export const metadata = {
    title: "Checkout Confirmation - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <CheckoutConfirmation/>
    </>
  )
}
