import React from 'react'
import Wishlist from '../Components/Wishlist';



export const metadata = {
    title: "Wishlist - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <Wishlist/>
    </>
  )
}
