import React from 'react'
import ConsBages from '../Components/ConsBages';
import CheckoutReview from '../Components/CheckoutReview';

export const metadata = {
    title: "Checkout Review - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <CheckoutReview/>
    </>
  )
}
