import React from 'react'
import LoginCard from '../Components/LoginCard'


export const metadata = {
    title: "Login - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
    return (
        <>
            <LoginCard/>
        </>
    )
}
