import React from 'react'
import CheckoutDelivery from '../Components/CheckoutDelivery';


export const metadata = {
    title: "Checkout Devilery - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <CheckoutDelivery/>
    </>
  )
}
