import React from 'react'
import ManageAddress from '../Components/ManageAddress';


export const metadata = {
    title: "Manage Address - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <ManageAddress/>
    </>
  )
}
