import React from 'react'
import Home from './Components/Home';


export const metadata = {
  title: "Monsta-Furniture",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <Home/>
    </>
  )
}

