import React from 'react'
import OrderHistory from '../Components/OrderHistory';

export const metadata = {
    title: "Order History - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <OrderHistory/>
    </>
  )
}
