import React from 'react'
import AccountPage from '../Components/AccountPage';


export const metadata = {
    title: "Account - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <AccountPage/>
    </>
  )
}
