import React from 'react'


export const metadata = {
    title: "About Us",
    description: "Generated by create next app",
  };
export default function page() {
  return (
    <>
      About us
    </>
  )
}
