import React from 'react'
import CheckoutAddress from '../Components/CheckoutAddress';


export const metadata = {
    title: "Checkout Address - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <CheckoutAddress/>
    </>
  )
}
