import React from 'react'
import ContactUsBG from '../Components/ContactUsBG'
import ContactUsContent from '../Components/ContactUsContent';


export const metadata = {
    title: "Contact Us - Online furniture store",
    description: "Generated by create next app",
  };




export default function page() {
  return (
    <>
      <ContactUsBG/>
      <ContactUsContent/>
    </>
  )
}
