import React from 'react'
import ChangePassword from '../Components/ChangePassword'


export const metadata = {
    title: "Change Password - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <ChangePassword/>
    </>
  )
}
