import React from 'react'
import Products from '../Components/Products';


export const metadata = {
    title: "Products - Online furniture store",
    description: "Generated by create next app",
  };


export default function page() {
  return (
    <>
      <Products/>
    </>
  )
}
