import React from 'react'
import ProfileInfo from '../Components/ProfileInfo';


export const metadata = {
    title: "Profile-Info - Online furniture store",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
      <ProfileInfo/>
    </>
  )
}
